// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");

@test:Config {}
isolated function  testPost-/marketing/v3/transactional/single-email/send_sendEmail() {
}

@test:Config {}
isolated function  testGet-/marketing/v3/transactional/smtp-tokens_getTokensPage() {
}

@test:Config {}
isolated function  testPost-/marketing/v3/transactional/smtp-tokens_createToken() {
}

@test:Config {}
isolated function  testPost-/marketing/v3/transactional/smtp-tokens/{tokenId}/password-reset_resetPassword() {
}

@test:Config {}
isolated function  testDelete-/marketing/v3/transactional/smtp-tokens/{tokenId}_archiveToken() {
}

@test:Config {}
isolated function  testGet-/marketing/v3/transactional/smtp-tokens/{tokenId}_getTokenById() {
}
