// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
final Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");

// @test:Config {}
// isolated function  testPost-/marketing/v3/transactional/single-email/send_sendEmail() {
//     EmailSendStatusView|error response = baseClient->/marketing/v3/transactional/single-email/send.post();
// }

@test:Config {}
isolated function  testGet/marketing/v3/transactional/smtp-tokens_getTokensPage() {

    GetMarketingV3TransactionalSmtpTokens_gettokenspageQueries queries = {

    }
    
    CollectionResponseSmtpApiTokenViewForwardPaging|error response = check baseClient->/marketing/v3/transactional/smtp-tokens_getTokensPage.get();
    if response is CollectionResponseSmtpApiTokenViewForwardPaging {

    }
}

// @test:Config {}
// isolated function  testPost-/marketing/v3/transactional/smtp-tokens_createToken() {
//     SmtpApiTokenView|error response = baseClient->/marketing/v3/transactional/smtp-tokens
// }

// @test:Config {}
// isolated function  testPost-/marketing/v3/transactional/smtp-tokens/{tokenId}/password-reset_resetPassword() {
// }

// @test:Config {}
// isolated function  testDelete-/marketing/v3/transactional/smtp-tokens/{tokenId}_archiveToken() {
// }

// @test:Config {}
// isolated function  testGet-/marketing/v3/transactional/smtp-tokens/{tokenId}_getTokenById() {
// }
