[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.marketing.transactional"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot","marketing","transactional", "emails"]
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.transactional"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
